apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chatbot-0610 
  janus-idp.io/tekton: chatbot-0610
  backstage.io/kubernetes-id: chatbot-0610
  backstage.io/kubernetes-namespace: rhtap-app-development 
  app.kubernetes.io/part-of: chatbot-0610
resources: 
- application-dev.yaml